<?php

declare(strict_types=1);

$embedded = (string) ($_GET['embed'] ?? '') === '1';
$pageTitle = 'Descriptions';
$topNavSection = 'configuration';
$BODY_CLASS = 'hub-page descriptions-page-shell' . ($embedded ? ' embedded-page' : '');
require __DIR__ . '/ui_bootstrap.php';
$rows = $uiRepository->rows('descriptions');
$discoveredItems = $uiRepository->rows('discovered_items');
$installations = [];
foreach ($uiRepository->rows('installations') as $installation) { $id = (string) ($installation['installation_id'] ?? ''); if ($id !== '') $installations[$id] = (string) ($installation['display_name'] ?? $id); }
$additionalStylesheets = ['herika-descriptions.css?v=' . (string) filemtime(__DIR__ . '/css/herika-descriptions.css')];
include __DIR__ . '/tmpl/head.html';
if (!$embedded) include __DIR__ . '/tmpl/navbar.php';
?>
<main class="descriptions-page">
    <header class="page-header"><h1>Description Manager</h1><p class="page-subtitle">Create custom descriptions for Morrowind items and equipment that enhance NPC context</p></header>
    <?php if (($_GET['status'] ?? '') === 'saved'): ?><div class="description-notice">Changes saved.</div><?php endif; ?>
    <div class="content-grid">
        <section class="content-section"><h2>Batch Upload</h2><label>Select .csv file to upload:<input type="file" accept=".csv" disabled aria-disabled="true"></label><div class="button-group"><span class="status-control"><button type="button" class="action-button upload-csv" disabled>Upload CSV</button><?php echo almsivi_ui_feature_badge('config.descriptions.batch', true); ?></span><span class="status-control"><button type="button" class="action-button download-csv" disabled>Download Example CSV</button><?php echo almsivi_ui_feature_badge('config.descriptions.batch', true); ?></span><span class="status-control"><button type="button" class="action-button export-csv" disabled>Export Custom Descriptions</button><?php echo almsivi_ui_feature_badge('config.descriptions.batch', true); ?></span></div><p>Typed format: content file, record ID, display name, description, and installation scope.</p></section>
        <section class="content-section"><h2>Database Management</h2><p>Descriptions are keyed by Morrowind content file and record ID.</p><p>Only records present in the current bounded inventory or nearby-object context are injected.</p><div class="button-group"><span class="status-control"><button type="button" class="btn-danger" disabled>Factory Reset Item Override Table</button><?php echo almsivi_ui_feature_badge('config.descriptions.reset', true); ?></span></div></section>
    </div>
    <section class="full-width-section">
        <h2>&#x1F50E; Discovered OpenMW Items</h2>
        <p>Items are learned automatically from bounded inventory, equipment, and nearby-object context. Identity uses the winning content file and record ID; display names are metadata only.</p>
        <div class="table-container"><table><thead><tr><th>Base ID</th><th>Plugin</th><th>Name</th><th>Seen In</th><th>Status</th></tr></thead><tbody><?php foreach ($discoveredItems as $item): ?><tr><td><?php echo almsivi_ui_h($item['record_id']); ?></td><td><?php echo almsivi_ui_h($item['content_file']); ?></td><td><?php echo almsivi_ui_h($item['display_name'] ?? ''); ?></td><td><?php $sources=json_decode((string)($item['observed_sources']??'[]'),true);echo almsivi_ui_h(is_array($sources)?implode(', ',$sources):''); ?></td><td><?php echo $item['description_id'] ? 'Custom description' : 'Detected'; ?><?php if (!filter_var($item['active'] ?? false,FILTER_VALIDATE_BOOL)): ?> (inactive plugin)<?php endif; ?></td></tr><?php endforeach; ?><?php if ($discoveredItems === []): ?><tr><td colspan="5">No items have been discovered in game yet.</td></tr><?php endif; ?></tbody></table></div>
    </section>
    <section class="full-width-section">
        <h2 id="entries">&#x1F4CB; Descriptions Database</h2>
        <div class="action-container"><button type="button" class="action-button add-new" data-description-create>Add New Entry</button><div class="search-container"><input type="search" placeholder="Search descriptions..." data-description-search><button type="button" class="action-button edit">Search</button></div></div>
        <div class="filter-section"><strong>Filter by Name:</strong><div class="filter-buttons"><button type="button" class="alphabet-button active" data-letter="">All</button><?php foreach (range('A','Z') as $letter): ?><button type="button" class="alphabet-button" data-letter="<?php echo $letter; ?>"><?php echo $letter; ?></button><?php endforeach; ?></div></div>
        <section class="new-entry-panel" data-description-panel hidden><h2>Add New Entry</h2><form method="post" action="<?php echo almsivi_ui_h($managementBasePath . '/forms/description-save'); ?>"><input type="hidden" name="_csrf" value="<?php echo almsivi_ui_h($csrf); ?>"><div class="entry-form-grid"><label>Installation<select name="installation_id"><?php foreach ($installations as $id => $label): ?><option value="<?php echo almsivi_ui_h($id); ?>"><?php echo almsivi_ui_h($label); ?></option><?php endforeach; ?></select></label><label>Content file<input name="content_file" value="Morrowind.esm" maxlength="256" required></label><label>Record ID<input name="record_id" maxlength="256" required></label><label>Display name<input name="display_name" maxlength="256" required></label><label class="wide">Description<textarea name="description" maxlength="8192" required></textarea></label></div><div class="button-group"><button class="action-button add-new" type="submit">Save description</button><button type="button" class="action-button" data-description-cancel>Cancel</button></div></form></section>
        <div class="table-container"><table><thead><tr><th>Base ID</th><th>Plugin</th><th>Name</th><th>Description</th><th>Actions</th></tr></thead><tbody><?php foreach ($rows as $row): ?><tr data-description-row data-search="<?php echo almsivi_ui_h(strtolower((string) (($row['display_name'] ?? '') . ' ' . ($row['content_file'] ?? '') . ' ' . ($row['record_id'] ?? '')))); ?>"><td><?php echo almsivi_ui_h($row['record_id']); ?></td><td><?php echo almsivi_ui_h($row['content_file']); ?></td><td><?php echo almsivi_ui_h($row['display_name']); ?></td><td><?php echo almsivi_ui_h($row['description']); ?></td><td><details><summary>Edit</summary><form method="post" action="<?php echo almsivi_ui_h($managementBasePath . '/forms/description-save'); ?>"><input type="hidden" name="_csrf" value="<?php echo almsivi_ui_h($csrf); ?>"><input type="hidden" name="installation_id" value="<?php echo almsivi_ui_h($row['installation_id']); ?>"><input name="content_file" value="<?php echo almsivi_ui_h($row['content_file']); ?>" required><input name="record_id" value="<?php echo almsivi_ui_h($row['record_id']); ?>" required><input name="display_name" value="<?php echo almsivi_ui_h($row['display_name']); ?>" required><textarea name="description" required><?php echo almsivi_ui_h($row['description']); ?></textarea><button type="submit">Save</button></form></details><form method="post" action="<?php echo almsivi_ui_h($managementBasePath . '/forms/description-delete'); ?>"><input type="hidden" name="_csrf" value="<?php echo almsivi_ui_h($csrf); ?>"><input type="hidden" name="description_id" value="<?php echo almsivi_ui_h($row['description_id']); ?>"><button type="submit" class="btn-danger">Delete</button></form></td></tr><?php endforeach; ?><?php if ($rows === []): ?><tr><td colspan="5">No custom descriptions are configured.</td></tr><?php endif; ?></tbody></table></div>
    </section>
</main>
<script defer src="<?php echo almsivi_ui_h($webRoot); ?>/ui/js/descriptions.js?v=<?php echo almsivi_ui_h((string) filemtime(__DIR__ . '/js/descriptions.js')); ?>"></script>
<?php include __DIR__ . '/tmpl/footer.html'; ?>
