<?php
declare(strict_types=1);
$pageTitle='Narrator Management';$topNavSection='configuration';$BODY_CLASS='hub-page';require __DIR__.'/ui_bootstrap.php';
$installations=$uiRepository->rows('installations');$rows=$uiRepository->rows('narrator');$ttsRows=$uiRepository->rows('tts');$byInstallation=[];foreach($rows as$row)$byInstallation[(string)$row['installation_id']]=$row;
$requested=trim((string)($_GET['installation_id']??''));$installationId=$requested!==''&&array_filter($installations,static fn(array$r):bool=>$r['installation_id']===$requested)?$requested:(string)($installations[0]['installation_id']??'');$profile=$byInstallation[$installationId]??null;$content=is_array($profile['content']??null)?$profile['content']:[];$embedded=($_GET['embed']??'')==='1';
include __DIR__.'/tmpl/head.html';if(!$embedded)include __DIR__.'/tmpl/navbar.php';
?>
<main class="almsivi-page<?php echo $embedded?' embedded':''; ?>"><header class="almsivi-page-header"><div><h1>Narrator Management</h1><p>Optional narrator routing remains off unless explicitly enabled. Configure its persona, event categories, and voice here.</p></div><span class="almsivi-badge">Optional</span></header><?php if(isset($_GET['status'])): ?><div class="almsivi-status">Narrator profile saved.</div><?php endif; ?>
<?php if($installations===[]): ?><section class="almsivi-card almsivi-empty">Connect OpenMW once before configuring narration.</section><?php else: ?><div class="almsivi-toolbar"><label>Installation<select data-installation-select><?php foreach($installations as$row): ?><option value="<?php echo almsivi_ui_h($row['installation_id']); ?>"<?php echo $row['installation_id']===$installationId?' selected':''; ?>><?php echo almsivi_ui_h($row['display_name']); ?></option><?php endforeach; ?></select></label></div>
<section class="almsivi-card"><form method="post" action="<?php echo almsivi_ui_h($managementBasePath); ?>/forms/<?php echo $profile===null?'narrator-profile-create':'narrator-profile-revise'; ?>"><input type="hidden" name="_csrf" value="<?php echo almsivi_ui_h($csrf); ?>"><input type="hidden" name="installation_id" value="<?php echo almsivi_ui_h($installationId); ?>"><?php if($profile!==null): ?><input type="hidden" name="profile_id" value="<?php echo almsivi_ui_h($profile['profile_id']); ?>"><input type="hidden" name="base_content_json" value="<?php echo almsivi_ui_h(json_encode($content,JSON_UNESCAPED_SLASHES)); ?>"><?php endif; ?><div class="almsivi-form-grid">
<label>Name<input name="name" required value="<?php echo almsivi_ui_h($profile['name']??'The Narrator'); ?>"<?php echo $profile===null?'':' readonly'; ?>></label><label>Inline narration<select name="inline_narration_mode"><?php foreach(['Disabled','Narrator','NPC','Text Only']as$mode): ?><option<?php echo ($content['inline_narration_mode']??'Disabled')===$mode?' selected':''; ?>><?php echo almsivi_ui_h($mode); ?></option><?php endforeach; ?></select></label>
<?php foreach(['enabled'=>'Enable narrator routing','context_visibility'=>'Include narrator context in prompts','welcome_events'=>'Welcome narration','random_events'=>'Random narration','quest_events'=>'Quest narration','book_events'=>'Book narration']as$field=>$label): ?><label><span><input type="checkbox" name="<?php echo almsivi_ui_h($field); ?>" value="1"<?php echo ($content[$field]??false)===true?' checked':''; ?>> <?php echo almsivi_ui_h($label); ?></span></label><?php endforeach; ?>
<?php foreach(['biography'=>'Background','personality'=>'Personality','speech_style'=>'Speech style','goals'=>'Goals','notes'=>'Additional notes']as$field=>$label): ?><label class="wide"><?php echo almsivi_ui_h($label); ?><textarea name="<?php echo almsivi_ui_h($field); ?>"><?php echo almsivi_ui_h($content[$field]??''); ?></textarea></label><?php endforeach; ?>
<label>TTS connector<select name="tts_configuration_id"><option value="">Use installation default</option><?php foreach($ttsRows as$tts):if($tts['installation_id']!==$installationId)continue; ?><option value="<?php echo almsivi_ui_h($tts['configuration_id']); ?>"<?php echo (($content['routing']['tts_configuration_id']??'')===$tts['configuration_id'])?' selected':''; ?>><?php echo almsivi_ui_h($tts['name']); ?></option><?php endforeach; ?></select></label><label>Voice ID<input name="voice_id" value="<?php echo almsivi_ui_h($content['voice']['id']??''); ?>"></label><label>Voice language<input name="voice_language" value="<?php echo almsivi_ui_h($content['voice']['language']??'en'); ?>"></label>
<?php if($profile!==null): ?><label class="wide">Revision note<input name="change_reason" required value="Management narrator update"></label><?php endif; ?></div><div class="almsivi-actions"><button type="submit"><?php echo $profile===null?'Create Narrator Profile':'Save Revision'; ?></button><?php if($profile!==null): ?><span class="almsivi-muted">Revision <?php echo almsivi_ui_h($profile['current_revision']); ?></span><?php endif; ?></div></form><?php if($profile!==null): ?><form method="post" action="<?php echo almsivi_ui_h($managementBasePath); ?>/forms/narrator-profile-generate"><input type="hidden" name="_csrf" value="<?php echo almsivi_ui_h($csrf); ?>"><input type="hidden" name="profile_id" value="<?php echo almsivi_ui_h($profile['profile_id']); ?>"><p class="almsivi-muted">AI generation fills the narrator persona while preserving narrator enablement and voice routing.</p><button class="secondary" type="submit">Generate narrator profile with AI</button></form><?php endif; ?></section><?php endif; ?></main><?php include __DIR__.'/tmpl/footer.html'; ?>
