<?php
declare(strict_types=1);
$pageTitle='ALMSIVI NPCs';$topNavSection='configuration';$BODY_CLASS='hub-page';require dirname(__DIR__).'/ui_bootstrap.php';
$installations=$uiRepository->rows('installations');$requested=trim((string)($_GET['installation_id']??''));$installationId='';
foreach($installations as$row)if($requested!==''&&hash_equals((string)$row['installation_id'],$requested))$installationId=$requested;
if($installationId===''&&isset($installations[0]))$installationId=(string)$installations[0]['installation_id'];
if($installationId!=='')$productRepository->defaultCoreProfileForInstallation($installationId,gmdate('Y-m-d\TH:i:s\Z'),true);
$filter=static fn(array$rows):array=>array_values(array_filter($rows,static fn(array$row):bool=>(string)$row['installation_id']===$installationId));
$characters=$filter($uiRepository->rows('characters'));$allCharacterCount=count($characters);$state=(string)($_GET['state']??'all');if(!in_array($state,['all','favorites','locked','unlocked','generated'],true))$state='all';$query=mb_strtolower(mb_substr(trim((string)($_GET['q']??'')),0,100));
$characters=array_values(array_filter($characters,static function(array$row)use($state,$query):bool{$content=is_array($row['content']??null)?$row['content']:[];$management=is_array($content['management']??null)?$content['management']:[];if($state==='favorites'&&($management['favorite']??false)!==true)return false;if($state==='locked'&&($management['locked']??false)!==true)return false;if($state==='unlocked'&&($management['locked']??false)===true)return false;if($state==='generated'){$generated=false;foreach(($row['revisions']??[])as$revision)if(str_contains(mb_strtolower((string)($revision['reason']??'')),'ai profile generation')){$generated=true;break;}if(!$generated)return false;}if($query==='')return true;$identity=is_array($row['actor_identity']??null)?$row['actor_identity']:[];$haystack=mb_strtolower(implode("\n",[(string)($row['name']??''),(string)($identity['record_id']??''),(string)($identity['content_file']??''),(string)($content['biography']??''),(string)($content['personality']??''),(string)($content['notes']??'')]));return str_contains($haystack,$query);}));
$coreProfiles=$filter($uiRepository->rows('core_profiles'));$observed=$filter($uiRepository->rows('observed_npcs'));$preferences=$filter($uiRepository->rows('profile_preferences'));
$llm=$filter($uiRepository->rows('llm'));$tts=$filter($uiRepository->rows('tts'));$prompts=$filter($uiRepository->rows('prompts'));$voices=$filter($uiRepository->rows('voice_catalog'));
$defaultCore='';foreach($coreProfiles as$core)if(filter_var($core['default_npc'],FILTER_VALIDATE_BOOL))$defaultCore=(string)$core['core_profile_id'];
$embedded=isset($_GET['embed'])&&$_GET['embed']==='1';include dirname(__DIR__).'/tmpl/head.html';if(!$embedded)include dirname(__DIR__).'/tmpl/navbar.php';
?>
<main class="almsivi-page<?php echo $embedded?' embedded':''; ?>">
    <header class="almsivi-page-header"><div><h1>ALMSIVI NPCs</h1><p>Every NPC inherits Global Settings through one Core Profile; only explicit fields below override it.</p></div><div class="almsivi-badges"><span class="almsivi-badge default"><?php echo count($characters); ?> NPC profiles</span></div></header>
    <?php if(isset($_GET['status'])): ?><div class="almsivi-status">NPC profile change saved.</div><?php endif; ?>
    <?php if($installations===[]): ?><section class="almsivi-card almsivi-empty">Connect OpenMW and target an NPC to begin.</section><?php else: ?>
    <div class="almsivi-toolbar"><label>Installation<select data-installation-select><?php foreach($installations as$row): ?><option value="<?php echo almsivi_ui_h($row['installation_id']); ?>"<?php echo $row['installation_id']===$installationId?' selected':''; ?>><?php echo almsivi_ui_h($row['display_name']); ?></option><?php endforeach; ?></select></label><form method="get" class="almsivi-toolbar"><input type="hidden" name="installation_id" value="<?php echo almsivi_ui_h($installationId); ?>"><label>Search NPCs<input type="search" name="q" maxlength="100" value="<?php echo almsivi_ui_h($_GET['q']??''); ?>" placeholder="Search..."></label><label>Status<select name="state"><?php foreach(['all'=>'All NPCs','favorites'=>'Favorites','locked'=>'Locked','unlocked'=>'Unlocked','generated'=>'AI generated']as$value=>$label): ?><option value="<?php echo almsivi_ui_h($value); ?>"<?php echo $state===$value?' selected':''; ?>><?php echo almsivi_ui_h($label); ?></option><?php endforeach; ?></select></label><button class="secondary" type="submit">Filter NPCs</button></form><span class="almsivi-muted">Showing <?php echo count($characters); ?> of <?php echo $allCharacterCount; ?></span></div>
    <div class="almsivi-inheritance"><span>Global defaults</span><span>Assigned Core Profile</span><span class="active">NPC overrides</span></div>
    <section class="almsivi-card mb-3"><div class="almsivi-card-header"><div><h2>Add Morrowind NPC</h2><p class="almsivi-muted">Use the stable record ID and content file. OpenMW RefNum data is learned automatically when encountered.</p></div></div>
        <form method="post" action="<?php echo almsivi_ui_h($managementBasePath); ?>/forms/profile-create">
            <input type="hidden" name="_csrf" value="<?php echo almsivi_ui_h($csrf); ?>"><input type="hidden" name="installation_id" value="<?php echo almsivi_ui_h($installationId); ?>"><input type="hidden" name="management_fields" value="1">
            <div class="almsivi-form-grid"><label>NPC name<input name="name" required maxlength="256"></label><label>Core Profile<select name="core_profile_id" required><?php foreach($coreProfiles as$core): ?><option value="<?php echo almsivi_ui_h($core['core_profile_id']); ?>"<?php echo $core['core_profile_id']===$defaultCore?' selected':''; ?>><?php echo almsivi_ui_h($core['label']); ?></option><?php endforeach; ?></select></label><label>Record ID<input name="record_id" maxlength="256"></label><label>Content file<input name="content_file" maxlength="256" value="Morrowind.esm"></label><label>Voice sample<select name="voice_id"><option value="">Connector default</option><?php foreach($voices as$voice): ?><option value="<?php echo almsivi_ui_h($voice['voice_id']); ?>"><?php echo almsivi_ui_h($voice['display_name'].' — '.$voice['connector_name']); ?></option><?php endforeach; ?></select></label><label>Voice language<input name="voice_language" value="en"></label>
            <?php foreach(['prompt_head'=>'Prompt head (advanced system guidance)','core'=>'Core identity and boundaries','appearance'=>'Appearance','biography'=>'Biography','personality'=>'Personality','speech_style'=>'Speech style','occupation'=>'Occupation','skills'=>'Skills and capabilities','goals'=>'Goals','relationships'=>'Relationships','emote_moods'=>'Allowed moods and emotes','notes'=>'Notes']as$field=>$label): ?><label class="wide"><?php echo almsivi_ui_h($label); ?><textarea name="<?php echo almsivi_ui_h($field); ?>"></textarea></label><?php endforeach; ?><label>Gender<select name="gender"><option value="">Unspecified</option><option>Male</option><option>Female</option><option>Other</option></select></label><label>Race<input name="race"></label><label><span><input type="checkbox" name="favorite" value="1"> Favorite NPC</span></label><label><span><input type="checkbox" name="locked" value="1"> Lock against automatic AI profile generation</span></label></div>
            <?php $content=[];include __DIR__.'/tmpl/npc_override_fields.php'; ?><div class="almsivi-actions"><button type="submit">Create NPC Profile</button></div>
        </form>
    </section>
    <section class="almsivi-grid mb-3"><article class="almsivi-card"><h2>Import NPC profile</h2><form method="post" action="<?php echo almsivi_ui_h($managementBasePath); ?>/forms/profile-import"><input type="hidden" name="_csrf" value="<?php echo almsivi_ui_h($csrf); ?>"><input type="hidden" name="installation_id" value="<?php echo almsivi_ui_h($installationId); ?>"><label>Choose JSON file<input type="file" accept="application/json,.json" data-json-import-target="npc-profile-json"></label><label>Portable ALMSIVI profile JSON<textarea id="npc-profile-json" name="profile_json" required placeholder="Choose a JSON file or paste its contents here."></textarea></label><div class="almsivi-actions"><button type="submit">Import Profile</button></div></form></article>
    <article class="almsivi-card"><h2>NPC profile tools</h2><?php $preference=$preferences[0]??null; ?><form method="post" action="<?php echo almsivi_ui_h($managementBasePath); ?>/forms/profile-auto-lock"><input type="hidden" name="_csrf" value="<?php echo almsivi_ui_h($csrf); ?>"><input type="hidden" name="installation_id" value="<?php echo almsivi_ui_h($installationId); ?>"><label><span><input type="checkbox" name="enabled" value="1"<?php echo in_array($preference['auto_lock_on_edit']??true,[true,1,'1','t','true'],true)?' checked':''; ?>> Auto-lock NPC profiles after manual edits</span></label><button type="submit">Save Preference</button></form><?php foreach([['profile-bulk-generate','Generate','Generate unlocked NPC profiles'],['profile-bulk-unlock','Unlock','Unlock all NPC profiles'],['profile-bulk-delete','Delete','Delete all unlocked NPC profiles']]as[$route,$word,$label]): ?><form method="post" action="<?php echo almsivi_ui_h($managementBasePath); ?>/forms/<?php echo almsivi_ui_h($route); ?>"<?php echo $route==='profile-bulk-delete'?' data-confirm="Delete all unlocked NPC profiles?"':''; ?>><input type="hidden" name="_csrf" value="<?php echo almsivi_ui_h($csrf); ?>"><input type="hidden" name="installation_id" value="<?php echo almsivi_ui_h($installationId); ?>"><label><?php echo almsivi_ui_h($label); ?><input name="confirm" required placeholder="Type <?php echo almsivi_ui_h($word); ?>"></label><button class="<?php echo $route==='profile-bulk-delete'?'danger':'secondary'; ?>" type="submit"><?php echo almsivi_ui_h($label); ?></button></form><?php endforeach; ?></article></section>
    <?php if($observed!==[]): ?><section class="almsivi-card mb-3"><div class="almsivi-card-header"><h2>Observed in OpenMW</h2></div><div class="almsivi-grid"><?php foreach($observed as$npc): ?><article><strong><?php echo almsivi_ui_h($npc['display_name']?:$npc['record_id']); ?></strong><div class="almsivi-muted"><?php echo almsivi_ui_h($npc['record_id']); ?> · <?php echo almsivi_ui_h($npc['content_file']); ?></div><?php if(empty($npc['profile_id'])): ?><form method="post" action="<?php echo almsivi_ui_h($managementBasePath); ?>/forms/profile-create"><input type="hidden" name="_csrf" value="<?php echo almsivi_ui_h($csrf); ?>"><input type="hidden" name="installation_id" value="<?php echo almsivi_ui_h($installationId); ?>"><input type="hidden" name="core_profile_id" value="<?php echo almsivi_ui_h($defaultCore); ?>"><input type="hidden" name="name" value="<?php echo almsivi_ui_h($npc['display_name']?:$npc['record_id']); ?>"><input type="hidden" name="record_id" value="<?php echo almsivi_ui_h($npc['record_id']); ?>"><input type="hidden" name="content_file" value="<?php echo almsivi_ui_h($npc['content_file']); ?>"><button type="submit">Create profile</button></form><?php else: ?><span class="almsivi-badge">Profile exists</span><?php endif; ?></article><?php endforeach; ?></div></section><?php endif; ?>
    <section class="almsivi-grid">
    <?php foreach($characters as$npc):$content=is_array($npc['content'])?$npc['content']:[];$identity=is_array($npc['actor_identity'])?$npc['actor_identity']:[];$management=is_array($content['management']??null)?$content['management']:[];$voice=is_array($content['voice']??null)?$content['voice']:[]; ?>
        <article class="almsivi-card"><div class="almsivi-card-header"><div><h2><?php echo almsivi_ui_h($npc['name']); ?></h2><p class="almsivi-muted"><code><?php echo almsivi_ui_h($identity['record_id']??'unbound'); ?></code> · <?php echo almsivi_ui_h($identity['content_file']??''); ?></p></div><div class="almsivi-badges"><?php if(($management['locked']??false)===true): ?><span class="almsivi-badge">Locked</span><?php endif; ?><?php if(($management['favorite']??false)===true): ?><span class="almsivi-badge default">Favorite</span><?php endif; ?></div></div>
            <dl><dt>Core Profile</dt><dd><?php echo almsivi_ui_h($npc['core_profile_label']??'Default'); ?></dd><dt>Voice</dt><dd><?php echo almsivi_ui_h($voice['id']??'Connector default'); ?></dd><dt>Revision</dt><dd><?php echo almsivi_ui_h($npc['current_revision']); ?></dd></dl>
            <p><?php echo almsivi_ui_h(mb_strimwidth((string)($content['biography']??$content['personality']??'No biography yet.'),0,240,'…')); ?></p>
            <details><summary>Manage portrait</summary><form method="post" enctype="multipart/form-data" action="<?php echo almsivi_ui_h($webRoot); ?>/ui/core/profile_portrait.php"><input type="hidden" name="_csrf" value="<?php echo almsivi_ui_h($csrf); ?>"><input type="hidden" name="profile_id" value="<?php echo almsivi_ui_h($npc['profile_id']); ?>"><input type="hidden" name="action" value="upload"><label>PNG, JPEG, or WebP portrait<input name="portrait" type="file" accept="image/png,image/jpeg,image/webp,.png,.jpg,.jpeg,.webp" required></label><button class="secondary" type="submit">Upload portrait</button></form><?php if(is_array($content['portrait']??null)&&$content['portrait']!==[]): ?><img class="npc-profile-portrait" src="<?php echo almsivi_ui_h($webRoot); ?>/ui/core/profile_portrait.php?profile_id=<?php echo rawurlencode((string)$npc['profile_id']); ?>" alt="Portrait of <?php echo almsivi_ui_h($npc['name']); ?>"><form method="post" action="<?php echo almsivi_ui_h($webRoot); ?>/ui/core/profile_portrait.php" data-confirm="Delete this portrait?"><input type="hidden" name="_csrf" value="<?php echo almsivi_ui_h($csrf); ?>"><input type="hidden" name="profile_id" value="<?php echo almsivi_ui_h($npc['profile_id']); ?>"><input type="hidden" name="action" value="delete"><button class="danger" type="submit">Delete portrait</button></form><?php endif; ?></details>
            <details><summary>Edit NPC</summary><form method="post" action="<?php echo almsivi_ui_h($managementBasePath); ?>/forms/profile-revise">
                <input type="hidden" name="_csrf" value="<?php echo almsivi_ui_h($csrf); ?>"><input type="hidden" name="profile_id" value="<?php echo almsivi_ui_h($npc['profile_id']); ?>"><input type="hidden" name="base_content_json" value="<?php echo almsivi_ui_h(json_encode($content===[]?(object)[]:$content,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)); ?>"><input type="hidden" name="management_fields" value="1">
                <div class="almsivi-form-grid"><label>Core Profile<select name="core_profile_id" required><?php foreach($coreProfiles as$core): ?><option value="<?php echo almsivi_ui_h($core['core_profile_id']); ?>"<?php echo $core['core_profile_id']===$npc['core_profile_id']?' selected':''; ?>><?php echo almsivi_ui_h($core['label']); ?></option><?php endforeach; ?></select></label><label>Voice sample<select name="voice_id"><option value="">Connector default</option><?php foreach($voices as$voiceRow): ?><option value="<?php echo almsivi_ui_h($voiceRow['voice_id']); ?>"<?php echo ($voice['id']??null)===$voiceRow['voice_id']?' selected':''; ?>><?php echo almsivi_ui_h($voiceRow['display_name'].' — '.$voiceRow['connector_name']); ?></option><?php endforeach; ?></select></label><label>Voice language<input name="voice_language" value="<?php echo almsivi_ui_h($voice['language']??'en'); ?>"></label><label><span><input type="checkbox" name="locked" value="1"<?php echo ($management['locked']??false)===true?' checked':''; ?>> Locked</span></label><label><span><input type="checkbox" name="favorite" value="1"<?php echo ($management['favorite']??false)===true?' checked':''; ?>> Favorite</span></label>
                <?php foreach(['prompt_head'=>'Prompt head (advanced system guidance)','core'=>'Core identity and boundaries','appearance'=>'Appearance','biography'=>'Biography','personality'=>'Personality','speech_style'=>'Speech style','occupation'=>'Occupation','skills'=>'Skills and capabilities','goals'=>'Goals','relationships'=>'Relationships','emote_moods'=>'Allowed moods and emotes','notes'=>'Notes']as$field=>$label): ?><label class="wide"><?php echo almsivi_ui_h($label); ?><textarea name="<?php echo almsivi_ui_h($field); ?>"><?php echo almsivi_ui_h($content[$field]??''); ?></textarea></label><?php endforeach; ?><label>Gender<select name="gender"><?php foreach([''=>'Unspecified','Male'=>'Male','Female'=>'Female','Other'=>'Other']as$value=>$label): ?><option value="<?php echo almsivi_ui_h($value); ?>"<?php echo ($content['gender']??'')===$value?' selected':''; ?>><?php echo almsivi_ui_h($label); ?></option><?php endforeach; ?></select></label><label>Race<input name="race" value="<?php echo almsivi_ui_h($content['race']??''); ?>"></label></div>
                <?php include __DIR__.'/tmpl/npc_override_fields.php'; ?><label>Revision note<input name="change_reason" required maxlength="512" value="Management NPC update"></label><div class="almsivi-actions"><button type="submit">Save NPC Revision</button></div>
            </form></details>
            <details><summary>Revision history</summary><?php almsivi_ui_table(is_array($npc['revisions'])?$npc['revisions']:[],'No revisions.'); ?></details><div class="almsivi-actions"><form method="post" action="<?php echo almsivi_ui_h($managementBasePath); ?>/forms/profile-clone"><input type="hidden" name="_csrf" value="<?php echo almsivi_ui_h($csrf); ?>"><input type="hidden" name="profile_id" value="<?php echo almsivi_ui_h($npc['profile_id']); ?>"><label>Clone name<input name="name" required value="<?php echo almsivi_ui_h($npc['name'].' copy'); ?>"></label><button class="secondary" type="submit">Clone</button></form><form method="post" action="<?php echo almsivi_ui_h($managementBasePath); ?>/forms/profile-generate"><input type="hidden" name="_csrf" value="<?php echo almsivi_ui_h($csrf); ?>"><input type="hidden" name="profile_id" value="<?php echo almsivi_ui_h($npc['profile_id']); ?>"><button class="secondary" type="submit">Generate with AI</button></form><?php if(($management['locked']??false)!==true): ?><form method="post" action="<?php echo almsivi_ui_h($managementBasePath); ?>/forms/profile-delete" data-confirm="Delete this NPC profile?"><input type="hidden" name="_csrf" value="<?php echo almsivi_ui_h($csrf); ?>"><input type="hidden" name="profile_id" value="<?php echo almsivi_ui_h($npc['profile_id']); ?>"><button class="danger" type="submit">Delete</button></form><?php else: ?><span class="almsivi-muted">This profile is locked.</span><?php endif; ?></div>
        </article>
    <?php endforeach; ?>
    </section>
    <?php endif; ?>
</main>
<?php include dirname(__DIR__).'/tmpl/footer.html'; ?>
