<?php
declare(strict_types=1);
$pageTitle='Player Management';$topNavSection='configuration';$BODY_CLASS='hub-page';require dirname(__DIR__).'/ui_bootstrap.php';
$installations=$uiRepository->rows('installations');$rows=$uiRepository->rows('player');$byInstallation=[];foreach($rows as$row)$byInstallation[(string)$row['installation_id']]=$row;
$requested=trim((string)($_GET['installation_id']??''));$installationId=$requested!==''&&isset($byInstallation[$requested])?$requested:'';
if($installationId===''&&isset($installations[0]))$installationId=(string)$installations[0]['installation_id'];$profile=$byInstallation[$installationId]??null;
$content=is_array($profile['content']??null)?$profile['content']:[];$embedded=($_GET['embed']??'')==='1';
include dirname(__DIR__).'/tmpl/head.html';if(!$embedded)include dirname(__DIR__).'/tmpl/navbar.php';
?>
<main class="almsivi-page<?php echo $embedded?' embedded':''; ?>"><header class="almsivi-page-header"><div><h1>Player Management</h1><p>Describe the Nerevarine once so every NPC can understand the player profile, history, appearance, goals, and speech.</p></div><span class="almsivi-badge">Player layer</span></header>
<?php if(isset($_GET['status'])): ?><div class="almsivi-status">Player profile saved.</div><?php endif; ?>
<?php if($installations===[]): ?><section class="almsivi-card almsivi-empty">Connect OpenMW once before creating the player profile.</section><?php else: ?><div class="almsivi-toolbar"><label>Installation<select data-installation-select><?php foreach($installations as$row): ?><option value="<?php echo almsivi_ui_h($row['installation_id']); ?>"<?php echo $row['installation_id']===$installationId?' selected':''; ?>><?php echo almsivi_ui_h($row['display_name']); ?></option><?php endforeach; ?></select></label></div>
<section class="almsivi-card"><h2><?php echo $profile===null?'Create player profile':'Edit '.almsivi_ui_h($profile['name']); ?></h2><form method="post" action="<?php echo almsivi_ui_h($managementBasePath); ?>/forms/<?php echo $profile===null?'player-profile-create':'player-profile-revise'; ?>"><input type="hidden" name="_csrf" value="<?php echo almsivi_ui_h($csrf); ?>"><input type="hidden" name="installation_id" value="<?php echo almsivi_ui_h($installationId); ?>"><?php if($profile!==null): ?><input type="hidden" name="profile_id" value="<?php echo almsivi_ui_h($profile['profile_id']); ?>"><input type="hidden" name="base_content_json" value="<?php echo almsivi_ui_h(json_encode($content,JSON_UNESCAPED_SLASHES)); ?>"><?php endif; ?><div class="almsivi-form-grid">
<label>Name<input name="name" required maxlength="256" value="<?php echo almsivi_ui_h($profile['name']??''); ?>"<?php echo $profile===null?'':' readonly'; ?>></label>
<?php foreach(['appearance'=>'Appearance','biography'=>'Biography and backstory','personality'=>'Personality','goals'=>'Goals and motivations','speech_style'=>'Speech style','notes'=>'Additional roleplay notes']as$field=>$label): ?><label class="wide"><?php echo almsivi_ui_h($label); ?><textarea name="<?php echo almsivi_ui_h($field); ?>"><?php echo almsivi_ui_h($content[$field]??''); ?></textarea></label><?php endforeach; ?>
<?php if($profile!==null): ?><label class="wide">Revision note<input name="change_reason" required value="Management player update"></label><?php endif; ?></div><div class="almsivi-actions"><button type="submit"><?php echo $profile===null?'Create Player Profile':'Save Revision'; ?></button><?php if($profile!==null): ?><span class="almsivi-muted">Revision <?php echo almsivi_ui_h($profile['current_revision']); ?> · <?php echo almsivi_ui_h($profile['input_count']); ?> observed player messages</span><?php endif; ?></div></form><?php if($profile!==null&&(int)$profile['input_count']>0): ?><form method="post" action="<?php echo almsivi_ui_h($managementBasePath); ?>/forms/player-speech-style-generate"><input type="hidden" name="_csrf" value="<?php echo almsivi_ui_h($csrf); ?>"><input type="hidden" name="profile_id" value="<?php echo almsivi_ui_h($profile['profile_id']); ?>"><p class="almsivi-muted">Generate a speech-style suggestion from observed player messages without replacing the rest of the profile.</p><button class="secondary" type="submit">Generate Speech Style with AI</button></form><?php elseif($profile!==null): ?><p class="almsivi-muted">Speech-style generation becomes available after OpenMW records a player message.</p><?php endif; ?></section>
<?php if($profile!==null&&is_array($profile['latest_context']??null)): ?><details class="almsivi-card"><summary>Latest OpenMW player context</summary><?php almsivi_ui_table([$profile['latest_context']]); ?></details><?php endif; ?><?php endif; ?></main><?php include dirname(__DIR__).'/tmpl/footer.html'; ?>
