DROP TABLE IF EXISTS backup_records;
DROP TABLE IF EXISTS operational_audit;
DROP TABLE IF EXISTS action_delivery;
DROP TABLE IF EXISTS action_catalog;
DROP TABLE IF EXISTS autonomy_schedules;
DROP TABLE IF EXISTS narrative_records;
DROP TABLE IF EXISTS retrieval_traces;
DROP TABLE IF EXISTS knowledge_documents;
DROP TABLE IF EXISTS relationship_audit;
DROP TABLE IF EXISTS relationship_records;
DROP TABLE IF EXISTS memory_records;
DROP TABLE IF EXISTS configuration_revisions;
DROP TABLE IF EXISTS configuration_sets;
DROP TABLE IF EXISTS playthrough_revisions;
DROP TABLE IF EXISTS playthroughs;
DROP TABLE IF EXISTS profile_revisions;
DROP TABLE IF EXISTS profiles;
DROP TABLE IF EXISTS browser_sessions;
DROP TABLE IF EXISTS pairing_tokens;
ALTER TABLE installations DROP COLUMN IF EXISTS revoked_at;
ALTER TABLE installations DROP COLUMN IF EXISTS display_name;
