DELETE FROM lorkhan_internal.core_tts_pronunciation
WHERE is_builtin = true;

-- Joined phonetic spellings avoid the artificial pauses that several TTS engines
-- introduce at hyphens. Azura and Nerevar intentionally use the engine's native reading.
INSERT INTO lorkhan_internal.core_tts_pronunciation(source_text,spoken_text,is_builtin)
VALUES
    ('Morrowind','Moreohwind',true),
    ('Vvardenfell','Vardenfell',true),
    ('Nerevarine','Nerevareen',true),
    ('Dagoth Ur','Dagoth Oor',true),
    ('Lorkhan','Lorkahn',true),
    ('Chimer','Kymer',true),
    ('Dwemer','Dwehmur',true),
    ('Bosmer','Bozmer',true),
    ('Khajiit','Kahjeet',true),
    ('Hlaalu','Hlaloo',true),
    ('Telvanni','Telvahnee',true),
    ('Almalexia','Almalexeeah',true),
    ('Sotha Sil','Sotha Seel',true),
    ('Vivec','Vihveck',true),
    ('Daedra','Daydra',true),
    ('Daedric','Daydrick',true),
    ('Tribunal','Trybyoonal',true),
    ('Resdayn','Rezdayn',true),
    ('Hortator','Hortahter',true),
    ('Balmora','Balmorah',true),
    ('Seyda Neen','Sayda Neen',true),
    ('Ald''ruhn','Auldroon',true),
    ('Gnisis','Neesis',true),
    ('Molag Mar','Mohlahg Mar',true),
    ('Maar Gan','Mar Gahn',true),
    ('Pelagiad','Pellajeead',true),
    ('Suran','Soorahn',true),
    ('Sadrith Mora','Sadrith Morah',true),
    ('Dagon Fel','Daygon Fell',true),
    ('Akulakhan','Akoolakahn',true),
    ('Numidium','Newmidium',true),
    ('Corprus','Korprus',true),
    ('Kwama','Kwamah',true),
    ('Guar','Gwar',true),
    ('N''wah','Enwah',true),
    ('S''wit','Swit',true),
    ('Caius Cosades','Kyus Cosahdees',true),
    ('Divayth Fyr','Divayth Fear',true),
    ('Yagrum Bagarn','Yahgrum Bagarn',true),
    ('Urshilaku','Urshilakoo',true),
    ('Ashkhan','Ashkahn',true),
    ('Velothi','Vellothee',true),
    ('Kogoruhn','Kogoroon',true),
    ('Muatra','Mooahtra',true),
    ('Kagrenac','Kagrenack',true),
    ('Sheogorad','Sheeogorad',true)
ON CONFLICT DO NOTHING;
