DELETE FROM lorkhan_internal.core_tts_pronunciation
WHERE is_builtin = true;

INSERT INTO lorkhan_internal.core_tts_pronunciation(source_text,spoken_text,is_builtin)
VALUES
    ('Morrowind','More-oh-wind',true),
    ('Vvardenfell','Var-den-fell',true),
    ('Nerevar','neh-ra-var',true),
    ('Nerevarine','Neh-reh-var-een',true),
    ('Dagoth Ur','Dag-oth Oor',true),
    ('Lorkhan','Lor-kahn',true),
    ('Dunmer','Dun-mer',true),
    ('Chimer','Ky-mer',true),
    ('Dwemer','Dweh-mer',true),
    ('Altmer','Alt-mer',true),
    ('Bosmer','Boz-mer',true),
    ('Khajiit','Kah-jeet',true),
    ('Hlaalu','Hlah-loo',true),
    ('Telvanni','Tel-vahn-ee',true),
    ('Redoran','Red-or-an',true),
    ('Indoril','In-dor-il',true),
    ('Almalexia','Al-ma-lex-ee-ah',true),
    ('Sotha Sil','Soh-tha Seel',true),
    ('Vivec','Vih-vek',true),
    ('Azura','ah-zu-ra',true),
    ('Daedra','Day-dra',true),
    ('Daedric','Day-drick',true),
    ('Tribunal','Try-byoo-nal',true),
    ('Resdayn','Rez-dayn',true),
    ('Hortator','Hor-tah-tor',true),
    ('Ashlander','Ash-land-er',true),
    ('Balmora','Bal-more-ah',true),
    ('Seyda Neen','Say-dah Neen',true),
    ('Ald''ruhn','Auld-roon',true),
    ('Gnisis','Nigh-sis',true),
    ('Molag Mar','Moe-lag Mar',true),
    ('Maar Gan','Mar Gahn',true),
    ('Pelagiad','Pell-ah-jee-ad',true),
    ('Suran','Soo-rahn',true),
    ('Sadrith Mora','Sad-rith More-ah',true),
    ('Dagon Fel','Day-gon Fell',true),
    ('Akulakhan','Ah-koo-lah-kahn',true),
    ('Numidium','New-mid-ee-um',true),
    ('Wraithguard','Rayth-guard',true),
    ('Keening','Kee-ning',true),
    ('Corprus','Kor-prus',true),
    ('Kwama','Kwah-mah',true),
    ('Guar','Gwar',true),
    ('N''wah','En-wah',true),
    ('S''wit','Swit',true),
    ('Caius Cosades','Kye-us Koh-sah-dees',true),
    ('Divayth Fyr','Dih-vayth Fear',true),
    ('Yagrum Bagarn','Yah-grum Bah-garn',true),
    ('Urshilaku','Ur-shih-lah-koo',true),
    ('Ashkhan','Ash-kahn',true)
ON CONFLICT DO NOTHING;
