#!/bin/sh
### BEGIN INIT INFO
# Provides:          lorkhanserver-worker
# Required-Start:    $network $postgresql
# Required-Stop:     $network $postgresql
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: LORKHANserver durable job worker
### END INIT INFO

set -eu

name=lorkhanserver-worker
daemon=/usr/local/libexec/lorkhanserver-worker-loop
pidfile=/run/lorkhanserver-worker.pid
logfile=/var/log/lorkhanserver/worker.log

is_running() {
    start-stop-daemon --status --quiet --pidfile "$pidfile" --user lorkhan
}

case "${1:-}" in
    start)
        if is_running; then
            exit 0
        fi
        rm -f "$pidfile"
        start-stop-daemon --start --quiet --background --make-pidfile \
            --pidfile "$pidfile" --chuid lorkhan:lorkhan \
            --chdir /var/www/LORKHANserver/current --startas "$daemon" \
            --output "$logfile"
        ;;
    stop)
        if is_running; then
            start-stop-daemon --stop --quiet --retry TERM/35/KILL/5 \
                --pidfile "$pidfile" --user lorkhan --remove-pidfile
        else
            rm -f "$pidfile"
        fi
        ;;
    restart|force-reload)
        "$0" stop
        "$0" start
        ;;
    status)
        if is_running; then
            echo "$name is running"
            exit 0
        fi
        echo "$name is not running" >&2
        exit 3
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|force-reload|status}" >&2
        exit 2
        ;;
esac
